services:
  djs-bot:
    container_name: djs-bot
    build:
      context: ..
      dockerfile: ./docker/djs-bot/Dockerfile
    restart: "unless-stopped"
    init: true
    environment:
      - TOKEN=${TOKEN}
      - CLIENTID=${CLIENTID}
      - CLIENTSECRET=${CLIENTSECRET}
      - DEVUID=${DEVUID}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    stdin_open: true
    tty: true
    volumes:
      - ../djs-bot:/djs-bot
    depends_on:
      - postgres-db
      - lavalink
    ports:
      - "8080:8080"
      - "3001:3001"
    working_dir: /djs-bot
    command: ["npm", "run", "${ENABLE:-start}", "--loglevel=error"]
    env_file:
      - .env
      - lavalink.env

  dashboard:
    container_name: dashboard
    image: node:latest
    restart: "unless-stopped"
    init: true
    stdin_open: true
    tty: true
    volumes:
      - ../dashboard:/dashboard
    depends_on:
      - postgres-db
      - lavalink
    ports:
      - "3000:3000"
    working_dir: /dashboard
    command: sh -c "
      npm config set fund false &&
      npm config set audit false &&
      npm run build-and-start
      "

  postgres-db:
    image: postgres:16.4-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  lavalink:
    image: fredboat/lavalink:3.7.12
    container_name: lavalink
    restart: unless-stopped
    hostname: docker.lavalink
    user: root
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins
    ports:
      - 2333:2333
    env_file:
      - lavalink.env

volumes:
  postgres_data:
